name: CodeNav

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  version: '0.1.${{ github.run_number }}'
  dotnetVersion: '8'
  repoUrl: ${{ github.server_url }}/${{ github.repository }}
  vsixPath: ${{ github.workspace }}/src/bin/Release/net8.0-windows8.0/CodeNav.vsix

jobs:
  build:
    name: 🛠️ Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.dotnetVersion }}.x

      - name: Build VSIX
        run: dotnet publish src -p:Version=${{ env.version }}

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: CodeNav
          path: |
            ${{ env.vsixPath }}
            publish-manifest.json
            README.md

  release:
    if: github.ref_name == 'main'
    name: 🚀 Release
    needs: build
    runs-on: windows-latest
    environment: Release
    permissions:
        contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7

      - name: Tag release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: '${{ env.version }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          name: ${{ steps.tag_release.outputs.new_tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          artifacts: ${{ env.vsixPath }}
          skipIfReleaseExists: true